---
__default__:
  time: "0-01:00"
  threads: 1
  mem: 2G
  queue: "debug"
  error: "logs/%x_%j_%N.err"
  output: "logs/%x_%j_%N.log"
##################
### ASSIGNMENT ###
##################
assignment_hybridFWRead_get_reads_by_length:
  time: "0-10:00"
  threads: 1
  mem: 2G
  queue: "medium"
assignment_hybridFWRead_get_reads_by_cutadapt:
  time: "0-20:00"
  threads: 1
  mem: 4G
  queue: "medium"
assignment_merge:
  time: "0-08:00"
  queue: medium
assignment_fastq_split:
  time: "1-00:00"
  threads: 1
  mem: 10G
  queue: medium
assignment_mapping_bwa:
  time: "0-02:00"
  threads: 30
  mem: 10G
  queue: medium
assignment_collect:
  time: "1-12:00"
  threads: 30
  mem: 10G
  queue: medium
assignment_collectBCs:
  time: "2-04:00"
  threads: 20
  mem: 10G
  queue: medium
assignment_mapping_exact:
  time: "0-01:00"
  threads: 1
  mem: 10G
  queue: debug
assignment_statistic_totalCounts:
  time: "0-01:00"
  threads: 1
  queue: medium
  mem: 60G
assignment_statistic_assignedCounts:
  time: "0-01:00"
  threads: 1
  queue: medium
  mem: 10G
assignment_statistic_assignment:
  time: "0-01:00"
  threads: 1
  queue: medium
  mem: 40G
##############
### COUNTS ###
##############
counts_demultiplex_BAM_umi:
  time: "4-00:00"
  mem: 22G
  queue: "medium"
counts_demultiplex_mergeTrimReads_BAM_umi:
  time: "4-00:00"
  mem: 12G
  queue: "medium"
counts_umi_create_BAM:
  time: "4-00:00"
  mem: 12G
  queue: "medium"
counts_umi_raw_counts:
  time: "0-22:00"
  mem: 6G
  queue: "medium"
counts_noUMI_create_BAM:
  time: 4-00:00
  mem: 12G
  queue: medium
counts_filter_counts:
  time: 0-02:00
  queue: medium
counts_final_counts_samplerer:
  mem: 20G
  queue: medium

#########################
### (ASSIGNED) COUNTS ###
#########################

counts_dna_rna_merge_counts:
  time: "0-10:00"
  queue: "medium"

#######################
### ASSIGNED COUNTS ###
#######################

assigned_counts_dna_rna_merge:
  time: "4-00:00"
  mem: 20G
  queue: "medium"

assigned_counts_assignBarcodes:
  time: "4-00:00"
  queue: "medium"
  mem: 20G

assigned_counts_createAssignmentPickleFile:
  mem: 10G

assigned_counts_filterAssignment:
  time: "0-01:00"
  queue: "medium"
  mem: 15G

#################
### Statistic ###
#################

########################
### Statistic/counts ###
########################

statistic_counts_frequent_umis:
  time: "0-04:00"
  queue: "medium"

statistic_counts_barcode_base_composition:
  time: "1-00:00"
  queue: "medium"
  mem: 20G
statistic_counts_table:
  time: 0-02:00
  queue: medium

#############################
### Statistic/correlation ###
#############################

statistic_correlation_bc_counts_hist:
  time: "0-02:00"
  mem: 10G
  queue: "medium"

statistic_correlation_bc_counts:
  time: "0-02:00"
  mem: 20G
  queue: "medium"
statistic_correlation_bc_hist:
  time: "0-22:00"
  mem: 10G
  queue: "medium"
statistic_correlation_calculate:
  time: "0-02:00"
  mem: 10G
  queue: "medium"
statistic_correlation_hist_box_plots:
  time: "0-02:00"
  mem: 10G
  queue: "medium"

############################
### Statistic/bc_overlap ###
############################

statistic_bc_overlap_run:
  time: "0-05:00"
  mem: 25G
  queue: "medium"
