---
global:
  assignments:
    split_number: 30
assignments:
  assocBasic:
    bc_length: 15
    alignment_tool:
      tool: bbmap
      configs:
        sequence_length:
          min: 166
          max: 175
        alignment_start:
          min: 1
          max: 3
    FW:
      - data/SRR10800986_1.fastq.gz
    BC:
      - data/SRR10800986_2.fastq.gz
    REV:
      - data/SRR10800986_3.fastq.gz
    design_file: design.fa
    configs:
      default: {}
